
[workspace]
members = ["crates/*", "examples/*"]

[workspace.dependencies]
ash = { version = "0.37.1+1.3.235", default-features = false, features = ["linked", "debug"] }
ash-window = "0.12.0"
winit = "0.27.5"
raw-window-handle = "0.5.0"
serde = "1.0.145"
serde-xml-rs = "0.6.0"
